CXX = g++
CPPFLAGS = -std=c++11 -I.. $(OBJECTS)
INC_DIR = ..
OBJECTS = $(INC_DIR)/MinHeap.o $(INC_DIR)/TreeNode.o

all: test1-1 test1-2 test1-3 test1-4 test1-5 test1-6

tes1-1: test1-1.cpp 
	$(CXX)  -o test1-1 test1-1.cpp

tes1-2: test1-2.cpp 
	$(CXX)  -o test1-2 test1-2.cpp

tes1-3: test1-3.cpp 
	$(CXX)  -o test1-3 test1-3.cpp

tes1-4: test1-4.cpp 
	$(CXX)  -o test1-4 test1-4.cpp

tes1-5: test1-5.cpp 
	$(CXX)  -o test1-5 test1-5.cpp	

tes1-6: test1-6.cpp 
	$(CXX)  -o test1-6 test1-6.cpp				

clean:
	rm -f *.o test1-1 test1-2 test1-3 test1-4 test1-5 test1-6
